set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE SCHEMA IF NOT EXISTS $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON SCHEMA $APP_DB_NAME TO $APP_DB_USER;
EOSQL