version: "3.8"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=postgres
      - APP_DB_PASS=password
      - APP_DB_NAME="Trippin"
    ports:
      - 5432:5432
    volumes:
#      - ./db:/var/lib/postgresql/data
      - ./create-schema.sh:/docker-entrypoint-initdb.d/create-schema.sh
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      - spring.profiles.active=dev
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=password
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true