logging:
  level:
    org:
      springframework: INFO
odata:
  jpa:
    punit_name: Trippin
    root_packages: org.example.trippin
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;MODE=LEGACY;INIT=CREATE SCHEMA IF NOT EXISTS Trippin;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: false
  servlet:
    multipart:
      enabled: false

eclipselink:
  ddl:
    auto:
      create:
        delete: true