logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: Trippin
    root_packages: com.example.trippin
server:
  port: 9010
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
  flyway:
    password: ''
    schemas:
      - Trippin
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    user: sa
  servlet:
    multipart:
      enabled: false